// UNiBOX - generated sender -> category map.
//
// AUTO-GENERATED by tools/generate-rules.js from your reviewed sender rollup.
// Do not edit by hand -- re-run the generator to refresh it.
//
// byEmail:  exact sender address -> category (primary, highest precision)
// byDomain: whole domain -> category (only domains where every labelled
//           sender agreed on one category)
//
// This placeholder is empty until you run the generator. rules.js reads it
// (see routeOne) after the hardcoded trusted senders and before the
// keyword rules, so known senders are categorized locally with no LLM.
window.UNIBOX_SENDER_MAP = {
  byEmail: {},
  byDomain: {},
};
