// UNiBOX - generate senderMap.js from a reviewed sender-rollup CSV.
//
// Usage:
//   node tools/generate-rules.js path/to/unibox-sender-rollup.csv
//
// Reads the CSV exported from the popup (after you've filled/corrected the
// proposedCategory column) and writes ../senderMap.js with:
//   byEmail:  address -> category  (only addresses with ONE agreed category)
//   byDomain: domain  -> category  (only domains where every labelled sender
//                                   on that domain agreed on one category)
//
// Ambiguous addresses/domains (a shared mailing list labelled two ways, e.g.
// Batch25@ used by both Placement and Announcement senders) are LEFT OUT so
// they fall through to the display-name rules in rules.js. "Others" IS mapped
// (it is a real category now), so known promotions/DMs classify locally and
// never reach the LLM. Any legacy "Unsure" label is treated as Others.

const fs = require("fs");
const path = require("path");

const ALLOWED = ["Academic", "Announcement", "Placement", "Others"];

// Minimal RFC-4180-ish CSV parser (handles quotes, escaped quotes, newlines).
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field); field = "";
    } else if (c === "\n") {
      row.push(field); rows.push(row); row = []; field = "";
    } else if (c === "\r") {
      // ignore; handled with \n
    } else field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

function norm(s) { return (s || "").toString().trim().toLowerCase(); }

function main() {
  const csvPath = process.argv[2];
  if (!csvPath) {
    console.error("Usage: node tools/generate-rules.js <rollup.csv>");
    process.exit(1);
  }
  const text = fs.readFileSync(csvPath, "utf8");
  const rows = parseCsv(text).filter(function (r) { return r.length && r.some(function (c) { return c !== ""; }); });
  if (!rows.length) { console.error("Empty CSV."); process.exit(1); }

  const header = rows[0].map(function (h) { return h.trim(); });
  const col = {};
  header.forEach(function (h, i) { col[h] = i; });
  ["emails", "domains", "proposedCategory"].forEach(function (c) {
    if (col[c] === undefined) {
      console.error('Missing required column "' + c + '". Found: ' + header.join(", "));
      process.exit(1);
    }
  });

  // email -> Set(categories), domain -> Set(categories)
  const emailCats = {};
  const domainCats = {};
  let labelled = 0, badCat = 0;

  for (let i = 1; i < rows.length; i++) {
    const r = rows[i];
    let cat = (r[col.proposedCategory] || "").trim();
    if (!cat) continue;
    if (cat === "Unsure" || cat === "Hackathon") cat = "Others"; // retired labels -> catch-all
    if (ALLOWED.indexOf(cat) === -1) {
      badCat++;
      console.warn("  ! row " + (i + 1) + ': unknown category "' + cat + '" -- skipped');
      continue;
    }
    // Others IS a real category now (promotions/DMs), so it is mapped too --
    // that way known promotional senders classify locally and never hit the LLM.
    labelled++;

    (r[col.emails] || "").split(";").forEach(function (e) {
      const key = norm(e);
      if (!key) return;
      (emailCats[key] = emailCats[key] || {})[cat] = true;
    });
    (r[col.domains] || "").split(";").forEach(function (d) {
      const key = norm(d);
      if (!key) return;
      (domainCats[key] = domainCats[key] || {})[cat] = true;
    });
  }

  const byEmail = {};
  let emailConflicts = 0;
  Object.keys(emailCats).forEach(function (e) {
    const cats = Object.keys(emailCats[e]);
    if (cats.length === 1) byEmail[e] = cats[0];
    else emailConflicts++;
  });

  const byDomain = {};
  let domainConflicts = 0;
  Object.keys(domainCats).forEach(function (d) {
    const cats = Object.keys(domainCats[d]);
    if (cats.length === 1) byDomain[d] = cats[0];
    else domainConflicts++;
  });

  // Sort keys for a stable, readable file.
  function sortedObj(o) {
    const out = {};
    Object.keys(o).sort().forEach(function (k) { out[k] = o[k]; });
    return out;
  }

  const out =
    "// UNiBOX - generated sender -> category map.\n" +
    "//\n" +
    "// AUTO-GENERATED by tools/generate-rules.js. Do not edit by hand --\n" +
    "// re-run the generator to refresh it.\n" +
    "window.UNIBOX_SENDER_MAP = {\n" +
    '  byEmail: ' + JSON.stringify(sortedObj(byEmail), null, 2).replace(/\n/g, "\n  ") + ",\n" +
    '  byDomain: ' + JSON.stringify(sortedObj(byDomain), null, 2).replace(/\n/g, "\n  ") + ",\n" +
    "};\n";

  const outPath = path.join(__dirname, "..", "senderMap.js");
  fs.writeFileSync(outPath, out, "utf8");

  console.log("Wrote " + outPath);
  console.log("  labelled sender rows: " + labelled);
  console.log("  byEmail entries:      " + Object.keys(byEmail).length + (emailConflicts ? "  (" + emailConflicts + " conflicting addresses left out)" : ""));
  console.log("  byDomain entries:     " + Object.keys(byDomain).length + (domainConflicts ? "  (" + domainConflicts + " conflicting domains left out)" : ""));
  if (badCat) console.log("  rows with bad category: " + badCat);
}

main();
